Testing - Marking failed code formatting #332

diff --git a/.github/actions/clang-format-check/action.yml b/.github/actions/clang-format-check/action.yml
--- a/.github/actions/clang-format-check/action.yml
+++ b/.github/actions/clang-format-check/action.yml
@@ -61,7 +61,9 @@ runs:
       run: |
         git diff > format.patch
         if ((Get-Item format.patch).length -gt 0) {
+          echo "::error::Files need formatting. To fix: 1. Download format.patch 2. \"git apply format.patch\" 3. Commit and push"
           echo "has_changes=true" >> $env:GITHUB_OUTPUT
+          exit 1
         }
 
     - name: Upload patch
