Improve clang-format-check action to set output flag for formatting changes

diff --git a/.github/actions/clang-format-check/action.yml b/.github/actions/clang-format-check/action.yml
--- a/.github/actions/clang-format-check/action.yml
+++ b/.github/actions/clang-format-check/action.yml
@@ -60,6 +60,9 @@ runs:
       shell: pwsh
       run: |
         git diff > format.patch
+        if ((Get-Item format.patch).length -gt 0) {
+          echo "has_changes=true" >> $env:GITHUB_OUTPUT
+        }
 
     - name: Upload patch
       if: steps.git-check.outputs.has_changes == 'true'
@@ -72,11 +75,8 @@ runs:
       if: steps.git-check.outputs.has_changes == 'true'
       shell: pwsh
       run: |
-        if ((Get-Item format.patch).length -gt 0) {
-          echo "::error::Files need formatting. To fix: 1. Download format.patch 2. \"git apply format.patch\" 3. Commit and push"
-          echo "has_changes=true" >> $env:GITHUB_OUTPUT
-          exit 1
-        }
+        echo "::error::Files need formatting. To fix: 1. Download format.patch 2. \"git apply format.patch\" 3. Commit and push"
+        exit 1
 
 branding:
   icon: 'check-square'
